/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export { AdditionalServiceObject } from './models/AdditionalServiceObject';
export type { Address } from './models/Address';
export type { B2cplCityObject } from './models/B2cplCityObject';
export type { B2cplOrderCallData } from './models/B2cplOrderCallData';
export type { B2cplOrderCallRequest } from './models/B2cplOrderCallRequest';
export type { B2cplOrderCallResponse } from './models/B2cplOrderCallResponse';
export type { BoxberryCityObject } from './models/BoxberryCityObject';
export type { CalculatorDirection } from './models/CalculatorDirection';
export type { CalculatorIntervalsRequest } from './models/CalculatorIntervalsRequest';
export type { CalculatorIntervalsResponse } from './models/CalculatorIntervalsResponse';
export type { CalculatorIntervalsTariffResult } from './models/CalculatorIntervalsTariffResult';
export type { CalculatorPlace } from './models/CalculatorPlace';
export type { CalculatorRequest } from './models/CalculatorRequest';
export type { CalculatorToDoorResult } from './models/CalculatorToDoorResult';
export type { CalculatorToPointResult } from './models/CalculatorToPointResult';
export type { CancelCourierCallResponse } from './models/CancelCourierCallResponse';
export type { CancelOrderResponse } from './models/CancelOrderResponse';
export type { CdekCityObject } from './models/CdekCityObject';
export type { ColumnMap } from './models/ColumnMap';
export type { ColumnSettings } from './models/ColumnSettings';
export type { ConfirmOrderYataxiRequest } from './models/ConfirmOrderYataxiRequest';
export type { ConfirmOrderYataxiResponse } from './models/ConfirmOrderYataxiResponse';
export type { Connection } from './models/Connection';
export type { ConnectionSchema } from './models/ConnectionSchema';
export { Cost } from './models/Cost';
export type { CourierCallRequest } from './models/CourierCallRequest';
export type { CourierCallResponse } from './models/CourierCallResponse';
export type { CourierCar } from './models/CourierCar';
export type { CreateAddressCodeRequest } from './models/CreateAddressCodeRequest';
export type { CreateAddressCodeResponse } from './models/CreateAddressCodeResponse';
export type { CreateWarehouseRequest } from './models/CreateWarehouseRequest';
export type { CreateWarehouseResponse } from './models/CreateWarehouseResponse';
export type { DefaultData } from './models/DefaultData';
export type { DeleteOrderResponse } from './models/DeleteOrderResponse';
export type { DeliveryCostThreshold } from './models/DeliveryCostThreshold';
export type { DeliveryInterval } from './models/DeliveryInterval';
export type { DeliveryType } from './models/DeliveryType';
export type { Dimensions } from './models/Dimensions';
export type { DocumentsRequest } from './models/DocumentsRequest';
export type { DpdBindPreorderPickupRequest } from './models/DpdBindPreorderPickupRequest';
export type { DpdBindPreorderPickupResponse } from './models/DpdBindPreorderPickupResponse';
export type { DpdCityObject } from './models/DpdCityObject';
export type { ErrorOrderInfo } from './models/ErrorOrderInfo';
export { ExtendedOrderData } from './models/ExtendedOrderData';
export type { ExternalTrackingDeleteOrderResponse } from './models/ExternalTrackingDeleteOrderResponse';
export type { ExternalTrackingOrderResponse } from './models/ExternalTrackingOrderResponse';
export type { ExternalTrackingOrdersRequest } from './models/ExternalTrackingOrdersRequest';
export type { ExtraParam } from './models/ExtraParam';
export type { ExtraParamOnCourier } from './models/ExtraParamOnCourier';
export type { File } from './models/File';
export type { filterParam } from './models/filterParam';
export { Item } from './models/Item';
export type { LabelsRequest } from './models/LabelsRequest';
export type { limitParam } from './models/limitParam';
export type { ListConnectionResponse } from './models/ListConnectionResponse';
export type { LoginRequest } from './models/LoginRequest';
export type { LoginResponse } from './models/LoginResponse';
export type { LogsisConfirmOrderRequest } from './models/LogsisConfirmOrderRequest';
export type { LogsisConfirmOrderResponse } from './models/LogsisConfirmOrderResponse';
export type { LogsisUpdateWarehouseRequest } from './models/LogsisUpdateWarehouseRequest';
export type { LogsisUpdateWarehouseResponse } from './models/LogsisUpdateWarehouseResponse';
export type { offsetParam } from './models/offsetParam';
export type { OrderCourierResponse } from './models/OrderCourierResponse';
export type { OrderData } from './models/OrderData';
export type { OrderDataResponse } from './models/OrderDataResponse';
export type { OrderInfo } from './models/OrderInfo';
export type { OrderInfoCost } from './models/OrderInfoCost';
export type { OrderInfoData } from './models/OrderInfoData';
export type { OrderInfoResponse } from './models/OrderInfoResponse';
export type { OrderRequest } from './models/OrderRequest';
export type { OrderResponse } from './models/OrderResponse';
export type { OrderReturnData } from './models/OrderReturnData';
export type { OrderReturnRequest } from './models/OrderReturnRequest';
export type { OrderStatus } from './models/OrderStatus';
export type { OrdersUploadRequest } from './models/OrdersUploadRequest';
export type { OrderSyncResponse } from './models/OrderSyncResponse';
export type { OrderUploadItem } from './models/OrderUploadItem';
export type { OrderUploadResponse } from './models/OrderUploadResponse';
export type { PaginationMeta } from './models/PaginationMeta';
export type { Params } from './models/Params';
export type { PaymentMethod } from './models/PaymentMethod';
export type { PayReceiptData } from './models/PayReceiptData';
export type { PayReceiptFiscalData } from './models/PayReceiptFiscalData';
export type { PayReceiptFullResponse } from './models/PayReceiptFullResponse';
export type { PayReceiptItem } from './models/PayReceiptItem';
export type { PayReceiptRequest } from './models/PayReceiptRequest';
export type { PayReceiptResponse } from './models/PayReceiptResponse';
export type { PickupType } from './models/PickupType';
export type { Place } from './models/Place';
export type { PlacementCodeResponse } from './models/PlacementCodeResponse';
export type { PlaceResponse } from './models/PlaceResponse';
export type { PointObject } from './models/PointObject';
export type { PointOperation } from './models/PointOperation';
export type { PointType } from './models/PointType';
export type { ProviderObject } from './models/ProviderObject';
export type { ProviderStatus } from './models/ProviderStatus';
export type { Recipient } from './models/Recipient';
export type { ReturnAddress } from './models/ReturnAddress';
export type { ReturnCost } from './models/ReturnCost';
export type { ReturnItem } from './models/ReturnItem';
export type { SaveOwnerOfTheGoods } from './models/SaveOwnerOfTheGoods';
export type { SchemasConnectionResponse } from './models/SchemasConnectionResponse';
export type { Sender } from './models/Sender';
export type { ServerError } from './models/ServerError';
export { ServiceError } from './models/ServiceError';
export type { SignupUserRequest } from './models/SignupUserRequest';
export type { Sizes } from './models/Sizes';
export type { StatusCommon } from './models/StatusCommon';
export type { StatusHistoryByDate } from './models/StatusHistoryByDate';
export type { StatusHistoryByInterval } from './models/StatusHistoryByInterval';
export type { StatusIdsRequest } from './models/StatusIdsRequest';
export type { StatusObject } from './models/StatusObject';
export type { SuccessResponse } from './models/SuccessResponse';
export type { TariffObject } from './models/TariffObject';
export type { UpdateOrderItemsRequest } from './models/UpdateOrderItemsRequest';
export type { UserResponse } from './models/UserResponse';
export type { ValidateOrderResponse } from './models/ValidateOrderResponse';
export type { WarehouseBoxberry } from './models/WarehouseBoxberry';
export type { WarehouseCreateBoxberry } from './models/WarehouseCreateBoxberry';
export type { WarehouseInfoBoxberry } from './models/WarehouseInfoBoxberry';
export type { WaybillItem } from './models/WaybillItem';
export type { WebhookListResponse } from './models/WebhookListResponse';
export type { WebhookSubscribeRequest } from './models/WebhookSubscribeRequest';
export type { WebhookSubscribeResponse } from './models/WebhookSubscribeResponse';
export type { WebhookSubscriptionDeleteResponse } from './models/WebhookSubscriptionDeleteResponse';
export type { WorkingTime } from './models/WorkingTime';
export type { X5Warehouse } from './models/X5Warehouse';

export { ApiPayService } from './services/ApiPayService';
export { B2CplService } from './services/B2CplService';
export { BillingService } from './services/BillingService';
export { BoxberryService } from './services/BoxberryService';
export { CalculatorService } from './services/CalculatorService';
export { ConnectionsService } from './services/ConnectionsService';
export { CourierCallService } from './services/CourierCallService';
export { CseService } from './services/CseService';
export { DpdService } from './services/DpdService';
export { ExternalTrackingService } from './services/ExternalTrackingService';
export { ListsService } from './services/ListsService';
export { LogsisService } from './services/LogsisService';
export { OrderDocsService } from './services/OrderDocsService';
export { OrdersService } from './services/OrdersService';
export { StatusesService } from './services/StatusesService';
export { UsersService } from './services/UsersService';
export { WebhooksService } from './services/WebhooksService';
export { X5Service } from './services/X5Service';
export { YataxiService } from './services/YataxiService';
