/* tslint:disable */
/* eslint-disable */
/**
 * FBS Orders
 * <div class=\"description_important\"> <b>Methods for working with assembly orders of the DBW model (Delivery by Wildberries) are now in a <a href=\"https://dev.wildberries.ru/en/release-notes?id=312\">separate environment</a>. </b> </div>  Use the FBS Orders (Fulfillment by Seller) methods to:   - get information about [assembly orders](/openapi/orders-fbs#tag/FBS-Assembly-Orders) and their statuses, cancel assembly orders, and get stickers   - get, add, edit, and delete [metadata](/openapi/orders-fbs#tag/FBS-Metadata) for assembly orders   - manage [supplies](/openapi/orders-fbs#tag/FBS-Supplies)   - create, edit, and delete [passes](/openapi/orders-fbs#tag/FBS-Passes) to WB warehouses 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

export const BASE_PATH = "http://localhost".replace(/\/+$/, "");

export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

export interface RequestArgs {
    url: string;
    options: RawAxiosRequestConfig;
}

export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected axios: AxiosInstance = globalAxios) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath ?? basePath;
        }
    }
};

export class RequiredError extends Error {
    constructor(public field: string, msg?: string) {
        super(msg);
        this.name = "RequiredError"
    }
}

interface ServerMap {
    [key: string]: {
        url: string,
        description: string,
    }[];
}

export const operationServerMap: ServerMap = {
    "FBSAssemblyOrdersApi.apiV3OrdersClientPost": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSAssemblyOrdersApi.apiV3OrdersGet": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSAssemblyOrdersApi.apiV3OrdersNewGet": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSAssemblyOrdersApi.apiV3OrdersOrderIdCancelPatch": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSAssemblyOrdersApi.apiV3OrdersStatusHistoryPost": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSAssemblyOrdersApi.apiV3OrdersStatusPost": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSAssemblyOrdersApi.apiV3OrdersStickersCrossBorderPost": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSAssemblyOrdersApi.apiV3OrdersStickersPost": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSAssemblyOrdersApi.apiV3SuppliesOrdersReshipmentGet": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSMetadataApi.apiMarketplaceV3OrdersMetaPost": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSMetadataApi.apiMarketplaceV3OrdersOrderIdMetaCustomsDeclarationPut": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSMetadataApi.apiV3OrdersOrderIdMetaDelete": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSMetadataApi.apiV3OrdersOrderIdMetaExpirationPut": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSMetadataApi.apiV3OrdersOrderIdMetaGtinPut": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSMetadataApi.apiV3OrdersOrderIdMetaImeiPut": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSMetadataApi.apiV3OrdersOrderIdMetaSgtinPut": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSMetadataApi.apiV3OrdersOrderIdMetaUinPut": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSPassesApi.apiV3PassesGet": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSPassesApi.apiV3PassesOfficesGet": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSPassesApi.apiV3PassesPassIdDelete": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSPassesApi.apiV3PassesPassIdPut": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSPassesApi.apiV3PassesPost": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSSuppliesApi.apiMarketplaceV3SuppliesSupplyIdOrderIdsGet": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSSuppliesApi.apiMarketplaceV3SuppliesSupplyIdOrdersPatch": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSSuppliesApi.apiV3SuppliesGet": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSSuppliesApi.apiV3SuppliesPost": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSSuppliesApi.apiV3SuppliesSupplyIdBarcodeGet": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSSuppliesApi.apiV3SuppliesSupplyIdDelete": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSSuppliesApi.apiV3SuppliesSupplyIdDeliverPatch": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSSuppliesApi.apiV3SuppliesSupplyIdGet": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSSuppliesApi.apiV3SuppliesSupplyIdTrbxDelete": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSSuppliesApi.apiV3SuppliesSupplyIdTrbxGet": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSSuppliesApi.apiV3SuppliesSupplyIdTrbxPost": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "FBSSuppliesApi.apiV3SuppliesSupplyIdTrbxStickersPost": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
}
