/* tslint:disable */
/* eslint-disable */
/**
 * FBS Orders
 * <div class=\"description_important\"> <b>Methods for working with assembly orders of the DBW model (Delivery by Wildberries) are now in a <a href=\"https://dev.wildberries.ru/en/release-notes?id=312\">separate environment</a>. </b> </div>  Use the FBS Orders (Fulfillment by Seller) methods to:   - get information about [assembly orders](/openapi/orders-fbs#tag/FBS-Assembly-Orders) and their statuses, cancel assembly orders, and get stickers   - get, add, edit, and delete [metadata](/openapi/orders-fbs#tag/FBS-Metadata) for assembly orders   - manage [supplies](/openapi/orders-fbs#tag/FBS-Supplies)   - create, edit, and delete [passes](/openapi/orders-fbs#tag/FBS-Passes) to WB warehouses 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

