/* tslint:disable */
/* eslint-disable */
/**
 * Product Management
 * Manage content, prices and inventory
 *
 * The version of the OpenAPI document: products
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

export const BASE_PATH = "http://localhost".replace(/\/+$/, "");

export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

export interface RequestArgs {
    url: string;
    options: RawAxiosRequestConfig;
}

export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected axios: AxiosInstance = globalAxios) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath ?? basePath;
        }
    }
};

export class RequiredError extends Error {
    constructor(public field: string, msg?: string) {
        super(msg);
        this.name = "RequiredError"
    }
}

interface ServerMap {
    [key: string]: {
        url: string,
        description: string,
    }[];
}

export const operationServerMap: ServerMap = {
    "CategoriesSubjectsAndCharacteristicsApi.contentV2DirectoryColorsGet": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "CategoriesSubjectsAndCharacteristicsApi.contentV2DirectoryCountriesGet": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "CategoriesSubjectsAndCharacteristicsApi.contentV2DirectoryKindsGet": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "CategoriesSubjectsAndCharacteristicsApi.contentV2DirectorySeasonsGet": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "CategoriesSubjectsAndCharacteristicsApi.contentV2DirectoryTnvedGet": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "CategoriesSubjectsAndCharacteristicsApi.contentV2DirectoryVatGet": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "CategoriesSubjectsAndCharacteristicsApi.contentV2ObjectAllGet": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "CategoriesSubjectsAndCharacteristicsApi.contentV2ObjectCharcsSubjectIdGet": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "CategoriesSubjectsAndCharacteristicsApi.contentV2ObjectParentAllGet": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "CreatingProductCardsApi.contentV2BarcodesPost": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "CreatingProductCardsApi.contentV2CardsLimitsGet": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "CreatingProductCardsApi.contentV2CardsUploadAddPost": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "CreatingProductCardsApi.contentV2CardsUploadPost": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "InventoryApi.apiV3StocksWarehouseIdDelete": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "InventoryApi.apiV3StocksWarehouseIdPost": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "InventoryApi.apiV3StocksWarehouseIdPut": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "MediaFilesApi.contentV3MediaFilePost": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "MediaFilesApi.contentV3MediaSavePost": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "PricesAndDiscountsApi.apiV2BufferGoodsTaskGet": [
        {
            url: "https://discounts-prices-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "PricesAndDiscountsApi.apiV2BufferTasksGet": [
        {
            url: "https://discounts-prices-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "PricesAndDiscountsApi.apiV2HistoryGoodsTaskGet": [
        {
            url: "https://discounts-prices-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "PricesAndDiscountsApi.apiV2HistoryTasksGet": [
        {
            url: "https://discounts-prices-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "PricesAndDiscountsApi.apiV2ListGoodsFilterGet": [
        {
            url: "https://discounts-prices-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "PricesAndDiscountsApi.apiV2ListGoodsFilterPost": [
        {
            url: "https://discounts-prices-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "PricesAndDiscountsApi.apiV2ListGoodsSizeNmGet": [
        {
            url: "https://discounts-prices-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "PricesAndDiscountsApi.apiV2QuarantineGoodsGet": [
        {
            url: "https://discounts-prices-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "PricesAndDiscountsApi.apiV2UploadTaskClubDiscountPost": [
        {
            url: "https://discounts-prices-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "PricesAndDiscountsApi.apiV2UploadTaskPost": [
        {
            url: "https://discounts-prices-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "PricesAndDiscountsApi.apiV2UploadTaskSizePost": [
        {
            url: "https://discounts-prices-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "ProductCardsApi.contentV2CardsDeleteTrashPost": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "ProductCardsApi.contentV2CardsErrorListPost": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "ProductCardsApi.contentV2CardsMoveNmPost": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "ProductCardsApi.contentV2CardsRecoverPost": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "ProductCardsApi.contentV2CardsUpdatePost": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "ProductCardsApi.contentV2GetCardsListPost": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "ProductCardsApi.contentV2GetCardsTrashPost": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "SellerWarehousesApi.apiV3DbwWarehousesWarehouseIdContactsGet": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "SellerWarehousesApi.apiV3DbwWarehousesWarehouseIdContactsPut": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "SellerWarehousesApi.apiV3OfficesGet": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "SellerWarehousesApi.apiV3WarehousesGet": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "SellerWarehousesApi.apiV3WarehousesPost": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "SellerWarehousesApi.apiV3WarehousesWarehouseIdDelete": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "SellerWarehousesApi.apiV3WarehousesWarehouseIdPut": [
        {
            url: "https://marketplace-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "TagsApi.contentV2TagIdDelete": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "TagsApi.contentV2TagIdPatch": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "TagsApi.contentV2TagNomenclatureLinkPost": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "TagsApi.contentV2TagPost": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
    "TagsApi.contentV2TagsGet": [
        {
            url: "https://content-api.wildberries.ru",
            description: "No description provided",
        }
    ],
}
