/* tslint:disable */
/* eslint-disable */
/**
 * ApiShip
 * **Документация единого API логистических компаний**  **Дополнительная документация: [docs.apiship.ru](https://docs.apiship.ru)**  **Подробнее об ApiShip на [apiship.ru](https://apiship.ru) или задайте вопрос на [info@apiship.ru](mailto:info@apiship.ru  )** 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@apiship.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

