/* tslint:disable */
/* eslint-disable */
/**
 * Product Management
 * Use the methods in this section to:   - [create](/openapi/work-with-products#tag/Creating-Product-Cards) and [edit](/openapi/work-with-products#tag/Product-Cards) product cards   - get [product categories, subjects, characteristics, and brands](/openapi/work-with-products#tag/Categories-Subjects-and-Characteristics)   - upload [media files](/openapi/work-with-products#tag/Media-Files) for product cards   - set up [tags](/openapi/work-with-products#tag/Tags) for product search   - set [prices and discounts](/openapi/work-with-products#tag/Prices-and-Discounts)   - manage [product inventory](/openapi/work-with-products#tag/Seller-Warehouses-Inventory) and [warehouses](/openapi/work-with-products#tag/Seller-Warehouses), if you work with the sales model from the seller\'s warehouse 
 *
 * The version of the OpenAPI document: products
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

